# Pledge: I pledge my honor that I have abided by the Stevens Honor System.
# Name: Haig Emirzian

all:
	gcc -Wall -Werror -pedantic-errors -c utils.c insertion.c utils.o insertion.o -o sort
clean:
	rm -f *.o sort sort.exe